<?php

namespace Database\Factories;

use App\Models\Project;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\DB;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Project>
 */
class ProjectFactory extends Factory
{
    protected $model = Project::class;

    public function definition(): array
    {
        $clientId = DB::table('clients')->value('id') ?? DB::table('clients')->insertGetId([
            'name' => 'Client Seeder',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $categoryId = DB::table('project_categories')->value('id') ?? DB::table('project_categories')->insertGetId([
            'name' => 'Seeder Category',
            'description' => 'Generated by seeder',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $statusProjectId = DB::table('status_projects')->value('id') ?? DB::table('status_projects')->insertGetId([
            'name' => 'On Progress',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $userId = DB::table('users')->value('id');
        $quotationNumber = $this->faker->unique()->numerify(now()->format('Y') . '###');

        DB::table('quotations')->insert([
            'quotation_number' => $quotationNumber,
            'client_id' => $clientId,
            'no_quotation' => 'Q-SEED-' . $quotationNumber,
            'quotation_weeks' => '4',
            'quotation_value' => 100000000,
            'client_pic' => 'PIC Seeder',
            'user_id' => $userId,
            'status' => 'O',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        return [
            'project_name' => $this->faker->sentence(3),
            'categories_project_id' => $categoryId,
            'quotations_id' => $quotationNumber,
            'status_project_id' => $statusProjectId,
            'client_id' => $clientId,
            'po_date' => now()->toDateString(),
            'po_value' => 100000000,
        ];
    }
}
